//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvBackend.EFVersion
{
    using System;
    using System.Collections.Generic;
    
    public partial class KvPairTable
    {
        public System.Guid RootObjectId { get; set; }
        public System.Guid ObjectId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Schema { get; set; }
    
        public virtual RootObject RootObject { get; set; }
    }
}
