//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KvBackend.EFVersion
{
    using System;
    using System.Collections.Generic;
    
    public partial class RootObject
    {
        public RootObject()
        {
            this.KvPairTables = new HashSet<KvPairTable>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> OfferStartDate { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<KvPairTable> KvPairTables { get; set; }
    }
}
